### ISSUE TITLE
The vision

### ISSUE THREAD

**Issue by stephenplusplus** [stephenplusplus/gcloud-test#1]
``` sh
$ gcloud-test
Deploying project to a test server...
.... serial port output ....
Running npm test...
... users tests run ...
VM deleted
```

**Comment by stephenplusplus** [comment]
@callmehiphop useful?

**Comment by callmehiphop** [comment]
I like it, obviously way easier than dealing with docker. However, this would cost the user money, correct?

**Comment by stephenplusplus** [comment]
Yeah, I suppose it's a wee bit specific to what is convenient for me. Oh well, I'll still make it for gcloud-node, and if it's helpful for others, we'll see.
